apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80      # The port the service is exposed on
      targetPort: 5007 # The port your container is listening on
  type: LoadBalancer  # Change to ClusterIP or NodePort if needed
